# Generated by Django 4.0.6 on 2022-07-13 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Joueur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitch_link', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tournoi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('match1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match1', to='tournament.match')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamName', models.CharField(max_length=50)),
                ('joueurAdc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joueurAdc', to='tournament.joueur')),
                ('joueurJungle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joueurJungle', to='tournament.joueur')),
                ('joueurMid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joueurMid', to='tournament.joueur')),
                ('joueurSupport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joueurSupport', to='tournament.joueur')),
                ('joueurTop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joueurTop', to='tournament.joueur')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='match',
            name='teamBlue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teamBlue', to='tournament.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='teamRed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teamRed', to='tournament.team'),
        ),
        migrations.AddField(
            model_name='joueur',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.wallet'),
        ),
    ]
